#!/bin/sh
# Normal stuff
xsetroot -cursor_name left_ptr &
compton &
feh --bg-scale $HOME/Pictures/Backgrounds/Motherboard.jpg &
sxhkd &
termite &
launch.sh &
xfce4-power-manager
nm-applet &
setxkbmap -option caps:escape
# BSPWM Configs
bspc monitor eDP1 -d I II III IV V VI VII
bspc config border_width         1
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bpsc config click_to_focus true

bspc config focused_border_color '#b9b9b9'
bspc config normal_border_color '#525252'
bspc config presel_feedback_color '#7c7c7c'
bspc config focus_follows_pointer true 
