#!/bin/sh  

# BSPWM Configs
bspc monitor eDP1 -d I II III IV V VI VII
bspc config border_width         3
bspc config window_gap           1
bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

. "${HOME}/.cache/wal/colors.sh"
sxhkd & 
# Set the border colors.
bspc config normal_border_color "$color1"
bspc config focused_border_color "$color15"
bspc config presel_feedback_color "$color4" 
bspc config focus_follows_pointer true 

